version: "3"

services:
  database:
    build:
      context: ./database
    container_name: 'database'
    restart: 'always'
    ports:
      - "127.0.0.1:${HOST_MACHINE_MYSQL_PORT}:3306"
    volumes:
      - ${MYSQL_DATA_DIR-./data/mysql}:/var/lib/mysql
      - ${MYSQL_LOG_DIR-./logs/mysql}:/var/log/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
  server:
    build: ./server
    depends_on:
      - database
    expose:
      - ${SERVER_PORT}
    environment:
      API_HOST: ${API_HOST}
      APP_SERVER_PORT: ${APP_SERVER_PORT}
    ports:
      - ${APP_SERVER_PORT}:${APP_SERVER_PORT}
    volumes:
      - ./server/src:/app/BE/src
    # command: npm run build
    # command: node src/test.js
    # command: node src/Db.bs.js
    command: npm start
  client:
    build: ./client
    expose:
      - ${FE_APP_PORT}
    environment:
      - FE_APP_PORT=${FE_APP_PORT}
    ports:
      - ${FE_APP_PORT}:${FE_APP_PORT}
    volumes:
      - ./client/src:/app/FE/src
    links:
      - server
  #   command: npm start
